version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    image: postgres:alpine
    restart: always
    env_file:
      - .${NODE_ENV}.env
    ports:
      - 6000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile-app
    env_file:
      - .${NODE_ENV}.env  
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev      
volumes:
  pgdata:

